name: Test
on:
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.devcontainer/**'
      - '.github/**'
      - '.gitignore'
      - 'CONTRIBUTING.md'
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Add Wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose --features generation && cargo build --target wasm32-unknown-unknown --verbose --features generation
    - name: Run tests
      run: cargo test --verbose
    - name: Run doctests
      run: cargo test --doc --verbose --features generation
    - uses: actions/checkout@v1
